# Generated by Django 2.1.5 on 2020-10-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('Bike_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Bike_name', models.CharField(max_length=100)),
                ('Bike_make', models.CharField(max_length=100)),
                ('Bike_model', models.CharField(max_length=100)),
                ('Bike_year', models.CharField(max_length=100)),
            ],
        ),
    ]
