# Generated by Django 2.1.5 on 2020-10-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bike', '0002_remove_bike_bike_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='Bike_id',
            new_name='id',
        ),
    ]
