# Generated by Django 2.1.5 on 2020-09-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS_DATA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position_lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('position_long', models.DecimalField(decimal_places=15, max_digits=20)),
                ('distance', models.DecimalField(decimal_places=15, max_digits=20)),
                ('enhanced_altitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('altitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('enhanced_speed', models.DecimalField(decimal_places=15, max_digits=20)),
                ('speed', models.DecimalField(decimal_places=15, max_digits=20)),
                ('heart_rate', models.DecimalField(decimal_places=15, max_digits=20)),
                ('cadence', models.DecimalField(decimal_places=15, max_digits=20)),
                ('fractional_cadence', models.DecimalField(decimal_places=15, max_digits=20)),
                ('temperature', models.DecimalField(decimal_places=15, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
